### ISSUE TITLE
Android browser window is opening in new instance

### ISSUE THREAD

**Issue by aalasolutions-zz** [chemerisuk/cordova-plugin-browser#1]
I have tried this plugin, it is working fine on iOS but in my android app it opens the browser tab as a separate instance which I can see in my app drawer.

To do the experiment I have created a blank application and installed this plugin. This new blank app worked fine as expected.

Now I am not sure what to check and how to debug this.

Thanks

**Comment by chemerisuk** [comment]
Try to add into config.xml:
```xml
<preference name="AndroidLaunchMode" value="singleTask" />
```

**Comment by aalasolutions-zz** [comment]
cool. it did worked.

Thanks
