### ISSUE TITLE
window.close from inside the browser page not working

### ISSUE THREAD

**Issue by aalasolutions-zz** [chemerisuk/cordova-plugin-browser#2]
Hi Man, 

I'm back with another question :). Thanks for the first answer.

I have opened a paypal payment page using your plugin. Now when payment is done, I am using `window.close()` method. It is working fine on Android. But on iOS it just stays there and do nothing. 

Do you have any idea how I can close that

**Comment by nitsand** [comment]
**Did you get this working? How?**
window.close() as far as I understand is not supposed to be able to close own window, for security reasons...

**Comment by BRadHoc** [comment]
But within the context of this plugin, it makes sense to be able to close the browser from within the web page.

**Comment by marcellov7** [comment]
Has anyone found a way to close the browser tab?
Thank you

**Comment by chemerisuk** [comment]
I believe you can redirect webpage to custom schema url “$PACKAGE_NAME://“ . It should close your browser tab on both platforms

**Comment by marcellov7** [comment]
> I believe you can redirect webpage to custom schema url “$PACKAGE_NAME://“ . It should close your browser tab on both platforms

Thanks @chemerisuk, so you mean to use deep linking?
Because with some Android 10 versions we are able to close using singleTask, but this unfortunately does not seem to work on newer versions.

**Comment by marcellov7** [comment]
> I believe you can redirect webpage to custom schema url “$PACKAGE_NAME://“ . It should close your browser tab on both platforms 

Thanks, it worked using the custom schema url plugin.

**Comment by marcellov7** [comment]
> I believe you can redirect webpage to custom schema url “$PACKAGE_NAME://“ . It should close your browser tab on both platforms 

Thanks, it worked using the custom schema url plugin.
