### ISSUE TITLE
cordova-support-android-plugin dependency issue

### ISSUE THREAD

**Issue by hussain-github** [chemerisuk/cordova-plugin-browser#6]
Hi, 

After updating cordova-support-android-plugin to version 2.0.4, cordova-plugin-browser is no longer working. The message I am getting is:

`Version of installed plugin: "cordova-support-android-plugin@2.0.4" does not satisfy dependency plugin requirement "cordova-support-android-plugin@~1.0.0". Try --force to use installed plugin as dependency.`

When I use --force, the plugin does get installed but does not work.

Updating the plugin to be compatible with cordova-support-android-plugin@2.0.4 would be much appreciated.

**Comment by chemerisuk** [comment]
Hi @hussain-github , thanks for report, this is in my todo list.

**Comment by chemerisuk** [comment]
Done in v2.1.0

**Comment by hussain-github** [comment]
> Done in v2.1.0

Great. Thank you for your efforts.
